package com.detallsublim.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MensajeContactoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeContactoAllPropertiesEquals(MensajeContacto expected, MensajeContacto actual) {
        assertMensajeContactoAutoGeneratedPropertiesEquals(expected, actual);
        assertMensajeContactoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeContactoAllUpdatablePropertiesEquals(MensajeContacto expected, MensajeContacto actual) {
        assertMensajeContactoUpdatableFieldsEquals(expected, actual);
        assertMensajeContactoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeContactoAutoGeneratedPropertiesEquals(MensajeContacto expected, MensajeContacto actual) {
        assertThat(actual)
            .as("Verify MensajeContacto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeContactoUpdatableFieldsEquals(MensajeContacto expected, MensajeContacto actual) {
        assertThat(actual)
            .as("Verify MensajeContacto relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getAsunto()).as("check asunto").isEqualTo(expected.getAsunto()))
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getFechaEnvio()).as("check fechaEnvio").isEqualTo(expected.getFechaEnvio()))
            .satisfies(a -> assertThat(a.getAtendido()).as("check atendido").isEqualTo(expected.getAtendido()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMensajeContactoUpdatableRelationshipsEquals(MensajeContacto expected, MensajeContacto actual) {
        // empty method
    }
}
