package com.detallsublim.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolicitudPresupuestoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudPresupuestoAllPropertiesEquals(SolicitudPresupuesto expected, SolicitudPresupuesto actual) {
        assertSolicitudPresupuestoAutoGeneratedPropertiesEquals(expected, actual);
        assertSolicitudPresupuestoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudPresupuestoAllUpdatablePropertiesEquals(SolicitudPresupuesto expected, SolicitudPresupuesto actual) {
        assertSolicitudPresupuestoUpdatableFieldsEquals(expected, actual);
        assertSolicitudPresupuestoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudPresupuestoAutoGeneratedPropertiesEquals(SolicitudPresupuesto expected, SolicitudPresupuesto actual) {
        assertThat(actual)
            .as("Verify SolicitudPresupuesto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudPresupuestoUpdatableFieldsEquals(SolicitudPresupuesto expected, SolicitudPresupuesto actual) {
        assertThat(actual)
            .as("Verify SolicitudPresupuesto relevant properties")
            .satisfies(a -> assertThat(a.getNombreCliente()).as("check nombreCliente").isEqualTo(expected.getNombreCliente()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getNombreEmpresa()).as("check nombreEmpresa").isEqualTo(expected.getNombreEmpresa()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a -> assertThat(a.getFechaSolicitud()).as("check fechaSolicitud").isEqualTo(expected.getFechaSolicitud()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a ->
                assertThat(a.getObservacionesInternas()).as("check observacionesInternas").isEqualTo(expected.getObservacionesInternas())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudPresupuestoUpdatableRelationshipsEquals(SolicitudPresupuesto expected, SolicitudPresupuesto actual) {
        assertThat(actual)
            .as("Verify SolicitudPresupuesto relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
